### ISSUE TITLE
Request the full dataset

### ISSUE THREAD

**Issue by Ngqgq** [linjc16/R2-DDI#1]
Using instructions on your homepage, I open a link to look for the dataset, only to be told that the page is not available . So, could you provide me with the full data set? My email address is 740308103@qq.com.

**Comment by linjc16** [comment]
Thanks for pointing this out. I have update the dataset files. 

The drugbank dataset can be seen in dataset folder. The twosides dataset can be download at https://figshare.com/articles/dataset/R2-DDI_Twosides_Dataset/22495666.

**Comment by Ngqgq** [comment]
Thank you very much for your reply. Inspired by your homepage, I have obtained this data set through the paper GMPNN-CS, but when I ran it last night, I found that the files train.a, train.b, valid.a, valid.b, train.nega and other files are missing, maybe this can be achieved through some of your code, but I can't find these training files at the moment, so could you send these files again, or tell me how to get them?

**Comment by linjc16** [comment]
You can obtain them from `Data Preprocessing` in the README file. e.g.

python ddi_zoo/scripts/data_process/run_process_trans.py

bash ddi_zoo/scripts/data_process/run_binarize_trans.sh

**Comment by Ngqgq** [comment]
Thanks for your help,I'll try it later.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiacheng ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 晚上9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [linjc16/R2-DDI] Request the full dataset (Issue #1)





 
You can obtain them from Data Preprocessing in the README file. e.g.
 
python ddi_zoo/scripts/data_process/run_process_trans.py
 
bash ddi_zoo/scripts/data_process/run_binarize_trans.sh
