### ISSUE TITLE
 cannot find some functions

### ISSUE THREAD

**Issue by Ngqgq** [linjc16/R2-DDI#2]
I have downloaded fairseq. Neither from the fairseq folder of your github code nor the latest fairseq GitHub I can't find the molecule.py and doublemodel.py. This means that I cannot find the functions shown in the figure below. If it is convenient, can you tell me how you obtained these functions?
![git](https://user-images.githubusercontent.com/87457554/231379255-45304ab2-a9d1-4b7c-b835-7e4baf896afb.png)

**Comment by linjc16** [comment]
Thank you for your feedback. Something wrong with .gitignore files and R2-DDI repo did not contain fairseq.data. You can turn to download fairseq folder in this repo https://github.com/linjc16/Pisces. I will fix R2-DDI repo soon.
