### ISSUE TITLE
能否提供最终代码？

### ISSUE THREAD

**Issue by ydgxch** [linjc16/R2-DDI#4]
在复现代码中发现好多目录和数据都没有，能提供一份最终的代码吗？ 
谢谢！

**Comment by linjc16** [comment]
Thanks for your attention. You can list the detailed error messages here. Actually, the co-authors have checked the code and it is enough to run the experiments.

**Comment by ydgxch** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
