### ISSUE TITLE
Find a data problem: can't find valid.a-b.a.node_attr.idx etc.

### ISSUE THREAD

**Issue by Aitejiu** [linjc16/R2-DDI#6]
When I ran the code, I realized that I have a series of files for constructing the graphs that I can't find, and when I generate the data through the script, it doesn't work, can you please provide them to me? Or tell me how to construct these data, thank you!
The file name is: `valid.a-b.a.{attrs}.idx` The replacement characters in {attrs} are the following four
![image](https://github.com/linjc16/R2-DDI/assets/73458598/8b07e5dd-54cd-41f2-ac7c-2c303f142a30)

**Comment by linjc16** [comment]
Hi, you should prepare the data in the fairseq format. Run the following code:

python ddi_zoo/scripts/data_process/split_trans.py

python ddi_zoo/scripts/data_process/run_process_trans.py

bash ddi_zoo/scripts/data_process/run_binarize_trans.sh

**Comment by Aitejiu** [comment]
> Hi, you should prepare the data in the fairseq format. Run the following code:
> 
> python ddi_zoo/scripts/data_process/split_trans.py
> 
> python ddi_zoo/scripts/data_process/run_process_trans.py
> 
> bash ddi_zoo/scripts/data_process/run_binarize_trans.sh

Sorry I'm just now seeing your reply. I have followed the commands you have given in your home page, but that data still does not appear and I have checked the source code of run_binarize_trans.sh, which does not generate the code for valid.a-b.a.node_attr.idx. The only files that generate fairseq types are the following.
![image](https://github.com/linjc16/R2-DDI/assets/73458598/88835103-caf8-4c80-85bb-8bfd0c18b5f4)
There are no such data.
![image](https://github.com/linjc16/R2-DDI/assets/73458598/bbd15dd0-27df-4f5e-84ed-fc0fe2124b2c)

**Comment by linjc16** [comment]
Have you followed the readme to install fairseq? From the errors, I guess you install the fairseq directly by "pip install fairseq" without compiling the files in the repo. 

pip install fairseq
pip uninstall -y fairseq 

pip install ninja
python setup.py build_ext --inplace

**Comment by Aitejiu** [comment]
> Have you followed the readme to install fairseq? From the errors, I guess you install the fairseq directly by "pip install fairseq" without compiling the files in the repo.
> 
> pip install fairseq pip uninstall -y fairseq
> 
> pip install ninja python setup.py build_ext --inplace


I'm sorry to bother you again, but I made a mistake in the installation.
![image](https://github.com/linjc16/R2-DDI/assets/73458598/2c97f6a3-52de-4129-bb8b-d70948b0887c)
I tried to fix it as I searched online, using cd fairseq pip install --editable . /, but it still reports an error.
![image](https://github.com/linjc16/R2-DDI/assets/73458598/29e970ab-2b88-44ce-9e4a-341ecb204a13)
I used the docker file, but I made changes to the docker file because my machine `A6000` needs to run on pytorch 1.13.1 for it to work. The modified docker file is as follows.
```
FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu18.04

ENV LANG=C.UTF-8
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    openssh-server  unzip curl \
    cmake gcc g++ \
    iputils-ping net-tools  iproute2  htop xauth \
    tmux wget vim git bzip2 ca-certificates \
    libxrender1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
ENV PATH /opt/conda/bin:$PATH
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -ay && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> /etc/profile && \
    echo "conda activate base" >> /etc/profile

WORKDIR /root/code

ENV envname pytorch
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda create -y -n $envname python=3.8 && \
    conda activate $envname && \
    conda install -y pytorch==1.13.1 torchvision==0.14.1 pytorch-cuda=11.7 -c pytorch -c nvidia && \
    conda install -y tensorboard tqdm scipy scikit-learn && \
    git clone https://github.com/pytorch/fairseq && \
    cd fairseq && \
    git checkout dd74992d0d143155998e9ed4076826bcea80fb06 && \
    pip install  -e . && \
    chmod o+rwx -R /root && \
    chmod o+w -R /opt/conda/envs/${envname} && \
    cd .. && \
    conda install -y -c conda-forge rdkit=2020.09.5 && \
    conda install -y tensorflow=2.2.0 && \
    conda install -y -c conda-forge deepchem && \
    TORCH=1.13.1 && CUDA=cu117 && \
    pip install torch-scatter --no-index -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-sparse --no-index -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-cluster --no-index -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-spline-conv --no-index -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html && \
    pip install torch-geometric && \
    conda clean -ay && pip cache purge && \
    sed -i 's/conda activate base/conda activate '"$envname"'/g' /etc/profile

ENV MKL_THREADING_LAYER GNU
ENV PATH /opt/conda/envs/${envname}/bin:$PATH
EXPOSE 6006
RUN echo "export LANG=C.UTF-8" >> /etc/profile && \
    echo "export MKL_THREADING_LAYER=GNU" >> /etc/profile 
```
Then I had a problem with my container environment.
No matter what command I execute, it reports an error.

![image](https://github.com/linjc16/R2-DDI/assets/73458598/3f9790b4-3b6e-4c51-be81-4fd174e7bf20)

**Comment by Aitejiu** [comment]
> Have you followed the readme to install fairseq? From the errors, I guess you install the fairseq directly by "pip install fairseq" without compiling the files in the repo.
> 
> pip install fairseq pip uninstall -y fairseq
> 
> pip install ninja python setup.py build_ext --inplace

ok！I solved the problem, thank you!
